### ISSUE TITLE
any... Binary... Anyone?

### ISSUE THREAD

**Issue by rasmusolle** [CatinaCupGames/Sharp2D#20]

**Comment by hypereddie** [comment]
This is by no means production ready simply because it's not finished.

There are a lot of kinks that still need to be worked out, many features that still need to be added and a lot of the API needs to be reworked.

The best thing Sharp2D can do at the moment is prototyping (which is what I use it for atm), because it already has all the ground work done, and allows for a quick and easy way to show a basic demo of a game/concept without a lot of effort.

With this in mind, if you still want a binary I can provide one. But I recommend to either:

1. Fork the repo and link the project's source directly, as this allows you to fix any kinks you find in the engine and make PR's
2. Use a more, stable, C# engine (such as [monogame](http://www.monogame.net/))

**Comment by rasmusolle** [comment]
I want the binary because I cant get it to compile lel. And I want to test it, and not make the next Minecraft or something lel.
